### ISSUE TITLE
How to solve "Measured time too small to obtain meaningful results"

### ISSUE THREAD

**Issue by SnakeAha** [Irdroid/Pulp_Dhrystone#2]
I find this page from riscv-tests issues (https://github.com/riscv-software-src/riscv-tests/issues/138)
Now the Dhrystone is modificated to your version, but it show the result:

> Dhrystone Benchmark, Version C, Version 2.2
> Program compiled with 'register' attribute
> Using rdcycle(), HZ=38400000
> 
> Trying 500 runs through Dhrystone:
> CPU Clock MHz : 38.4
> REGVAL PCCR: d
> REGVAL PCMER: d
> REGVAL CYCLES: u
> REGVAL INSTRUCTIONS: u
> 
> Begin_time: u
> End_time: u
> User_time: u
> 
> Measured time too small to obtain meaningful results
> 
> Trying 5000 runs through Dhrystone:

Why the result of time is show by letters? Do you know how to solve this?
I use the RISCY core. If you have some advices about this problem please tell me. Thanks!

**Comment by Irdroid** [comment]
Looks like you are not enabling the performance counters in your code

**Comment by SnakeAha** [comment]
I use the Dhrystone like yours.
How can I do to enable the performance counters?
Should I do something with RTL？
Thanks for your reply!

**Comment by Irdroid** [comment]
write_csr(0xCC0,1);
write_csr(0xCC1,1)

Enables the performance counters for the risc-v core that I am using , refer to the the datasheet of your core and check what are the performance counters registers for your case.

The above write_csr functions are in dhrystone_main.c

**Comment by SnakeAha** [comment]
I follow your advise, now Dhrystone it can running.
Thanks for your reply !!!
It means a lot for me.
